name: goAIME
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - Flask==3.0.0
      - Flask-Cors==4.0.0
      - Flask-SQLAlchemy==3.0.5
      - Flask-JWT-Extended==4.6.0
      - pymupdf==1.25.3
      - PyPDF2==3.0.1
      - pdf2image==1.17.0
      - pymongo==4.11
      - numpy==1.26.3
      - scipy==1.11.4
      - pandas==2.1.4
      - torch==2.2.2
      - tensorflow==2.16.2
      - scikit-learn==1.3.2
      - aiohttp==3.9.1
      - selenium==4.16.0
      - webdriver-manager==4.0.1
      - pytest==7.4.3
      - pytest-flask==1.3.0
      - bcrypt==4.1.2
      - python-dotenv==1.0.0
      - matplotlib==3.8.2
      - seaborn==0.13.0
      - openai==1.61.1
      - aisuite==0.1.9
      - APScheduler==3.11.0
      - opencv-python==4.11.0.86
      - svgwrite==1.4.3
